Repository kyma-project/third-party-images, pull requests merged in 2021-08, with the labels that each got.

#112 K8S tools: update dependencies
  k8s-tools/Dockerfile
Labels: size/XS, lgtm

#113 Remove kazydek from CODEOWNERS & add NHingerl
  CODEOWNERS
Labels: documentation, size/XS, lgtm

#115 Update alpine version
  minio/Dockerfile
Labels: size/XS, lgtm

#117 update to fluent-bit 1.8.x
  fluent-bit/Dockerfile
  fluent-bit/Makefile
  fluent-bit/README.md
  fluent-bit/patch/REAMDE.md
  fluent-bit/patch/non-blocking-write/flb_engine.c
  fluent-bit/patch/non-blocking-write/flb_output.h
  fluent-bit/patch/non-blocking-write/flb_pipe.c
  fluent-bit/patch/non-blocking-write/flb_pipe.h
  fluent-bit/plugins/CMakeLists.txt
  fluent-bit/plugins/out_sequentialhttp/sequentialhttp.c
  fluent-bit/plugins/out_sequentialhttp/sequentialhttp.h
  fluent-bit/plugins/out_sequentialhttp/sequentialhttp_conf.c
  fluent-bit/plugins/out_sequentialhttp/sequentialhttp_conf.h
Labels: size/XXL, lgtm
