Repository kyma-project/third-party-images, pull requests merged in 2021-05, with the labels that each got.

#83 Makefiles: use generic makefile
  cloudsql-proxy/Makefile
  common/README.md
  common/generic_makefile.mk
  console-nginx/Makefile
  docker-registry/Makefile
  fluent-bit/Makefile
  grafana/Makefile
  jaeger-operator/Makefile
  k8s-tools/Dockerfile
  k8s-tools/Makefile
  kiali/Makefile
  kiwigrid-sidecar/Makefile
  minio-mc/Makefile
  minio/Makefile
  prometheus-node-exporter/Makefile
Labels: lgtm

#84 Makefile: fix post main
  common/generic_makefile.mk
  k8s-tools/Dockerfile
Labels: lgtm, size/XS

#87 Bump cloudsql-proxy alpine base image to 3.13.5
  cloudsql-proxy/Dockerfile
Labels: lgtm, size/XS

#89 Bump registry and minio base alpine image to version 3.15.5
  docker-registry/Dockerfile
  minio/Dockerfile
Labels: lgtm, size/XS

#88 Add etcd v3.3.25 image
  CODEOWNERS
  etcd/Dockerfile
  etcd/Makefile
  etcd/README.md
Labels: lgtm, size/M

#90 Enforce etcd image rebuild
  etcd/Dockerfile
Labels: lgtm, size/XS

#91 Upgrade Wookiee beings in the CODEOWNERS file
  CODEOWNERS
Labels: enhancement, lgtm, size/XS

#92 update base images of fluent-bit and k8s-sidecar
  fluent-bit/Dockerfile
  kiwigrid-sidecar/Dockerfile
Labels: lgtm, size/XS
