Repository kyma-project/third-party-images, pull requests merged in 2021-06, with the labels that each got.

#95 Update K8S tools - fix curl vulnerability
  k8s-tools/Dockerfile
Labels: lgtm, size/XS

#97 adding custom image for oauth2-proxy
  oauth2-proxy/Dockerfile
  oauth2-proxy/Makefile
  oauth2-proxy/README.md
Labels: lgtm, size/M

#98 update base images of several images
  fluent-bit/Dockerfile
  grafana/Dockerfile
  kiali/Dockerfile
  oauth2-proxy/Dockerfile
Labels: lgtm, size/S

#100 Reset grafana version to 7.4
  grafana/Makefile
  grafana/README.md
Labels: lgtm, size/XS

#102 Bump cloudsql-proxy image
  cloudsql-proxy/Dockerfile
  cloudsql-proxy/Makefile
Labels: lgtm, size/XS

#103 upgrade kiali to 1.36
  kiali/Dockerfile
  kiali/Makefile
  kiali/README.md
Labels: lgtm, size/XS

#99 Remove busola and console images
  console-nginx/Dockerfile
  console-nginx/Makefile
  console-nginx/README.md
Labels: lgtm, size/S

#105 upgrade of loki fluent-bit plugin to 2.2.1
  fluent-bit/Dockerfile
Labels: lgtm, size/XS
