Repository kyma-project/third-party-images, pull requests merged in 2021-09, with the labels that each got.

#118 update to fluent-bit 1.8.5
  fluent-bit/Dockerfile
  fluent-bit/Makefile
Labels: size/XS, lgtm

#121 added loki as new image
  loki/Dockerfile
  loki/Makefile
  loki/README.md
Labels: size/M, lgtm

#120 update to alpine 3.14.2
  fluent-bit/Dockerfile
  fluent-bit/Makefile
  fluent-bit/README.md
  grafana/Dockerfile
  kiali/Dockerfile
  kiwigrid-sidecar/Dockerfile
  oauth2-proxy/Dockerfile
  prometheus-node-exporter/Dockerfile
Labels: size/S, lgtm

#119 bump alpine version
  minio/Dockerfile
Labels: size/XS, lgtm

#122 update of kiali to 1.38.1
  kiali/Makefile
Labels: size/XS, lgtm

#125 update to fluent-bit 1.8.7
  fluent-bit/Dockerfile
  fluent-bit/Makefile
Labels: size/XS, lgtm

#123 Add kaniko-executer image
  CODEOWNERS
  kaniko-executer/Dockerfile
  kaniko-executer/Makefile
  kaniko-executer/README.md
Labels: size/L, lgtm

#126 Bump cloudsql-proxy img
  cloudsql-proxy/Dockerfile
  cloudsql-proxy/Makefile
Labels: size/XS, lgtm

#127 Update the minio to the last version with the Apache license
  minio/Dockerfile
Labels: size/XS, lgtm

#128 K8s-tools: bump Alpine
  k8s-tools/Dockerfile
Labels: size/XS, lgtm

#124 Bump alpine to 3.14.2 in etcd image
  etcd/Dockerfile
Labels: size/XS, lgtm
