Repository kyma-project/third-party-images, pull requests merged in 2021-11, with the labels that each got.

#144 update to kiwigrid sidecar 1.14
  kiwigrid-sidecar/Dockerfile
  kiwigrid-sidecar/Makefile
Labels: size/XS, lgtm

#142 Grafana Image now based on Grafana Watcher
  grafana/Dockerfile
  grafana/go.mod
  grafana/go.sum
  grafana/main.go
  grafana/main_test.go
Labels: size/L, lgtm

#145 Add `-U` parameter to the apk method
  minio/Dockerfile
Labels: size/XS, lgtm

#147 Upgrade kaniko version
  kaniko-executer/Dockerfile
  kaniko-executer/Makefile
Labels: size/XS, lgtm

#148 Bump cloud-sql-proxy version to 1.27.0
  cloudsql-proxy/Dockerfile
  cloudsql-proxy/Makefile
Labels: size/XS, lgtm

#146 Trigger the `docker-registry` build
  docker-registry/Dockerfile
Labels: size/S, lgtm, area/security

#149 Add the `ca-certificates` and the `apache2-utils` packages to the docker-registry image
  docker-registry/Dockerfile
Labels: bug, size/XS, lgtm, area/serverless

#151 update fluent-bit to 1.8.10
  fluent-bit/Dockerfile
  fluent-bit/Makefile
Labels: size/XS, lgtm

#152 update oauth2-proxy to 7.2
  oauth2-proxy/Dockerfile
  oauth2-proxy/Makefile
  oauth2-proxy/README.md
Labels: size/XS, lgtm
