Repository kyma-project/third-party-images, pull requests merged in 2022-05, with the labels that each got.

#224 update to fluent-bit 1.9.3
  fluent-bit/Makefile
Labels: size/XS, lgtm

#225 Bump golang
  kaniko-executer/Dockerfile
Labels: size/XS, lgtm

#226 Bump cloudsql-proxy to v1.30.1
  cloudsql-proxy/Dockerfile
  cloudsql-proxy/Makefile
Labels: size/XS, lgtm

#227 Use golang 1.18.1 in docker registry
  docker-registry/Dockerfile
Labels: size/XS, lgtm

#228 Update k8s-tools image
  k8s-tools/Dockerfile
Labels: size/XS, lgtm

#229 Bump debian and alpine base images
  fluent-bit/Dockerfile
  grafana/Dockerfile
  loki/Dockerfile
  oauth2-proxy/Dockerfile
  prometheus-node-exporter/Dockerfile
Labels: size/S, lgtm

#230 Use upstream Fluent Bit base image
  fluent-bit/Dockerfile
  fluent-bit/Makefile
Labels: size/M, lgtm

#231 update to grafana 7.5.16
  grafana/Makefile
Labels: size/XS, lgtm

#233 Clean bump of k8s-tools image
  k8s-tools/Dockerfile
Labels: size/XS, lgtm

#234 update to oauth2-proxy 7.3.0
  oauth2-proxy/Makefile
Labels: size/XS, lgtm
