Repository kyma-project/third-party-images, pull requests merged in 2022-09, with the labels that each got.

#259 update to fluent 1.9.8
  fluent-bit/Dockerfile
  fluent-bit/Makefile
Labels: size/S, lgtm

#261 Fix jaeger-operator build image version
  jaeger-operator/Dockerfile
  jaeger-operator/Makefile
Labels: size/XS, lgtm

#263 Build a custom grafana binary to update the golang version
  grafana/Dockerfile
  grafana/Makefile
  grafana/run.sh
Labels: size/L, lgtm

#264 update fluent-bit to 1.9.9
  fluent-bit/Makefile
Labels: size/XS, lgtm

#265 update to node-exporter 1.4.0
  prometheus-node-exporter/Dockerfile
  prometheus-node-exporter/Makefile
Labels: size/S, lgtm
