Repository kyma-project/third-party-images, pull requests merged in 2022-02, with the labels that each got.

#174 One place to store minio tag
  minio/Dockerfile
  minio/Makefile
Labels: size/S, lgtm

#178 update jaeger operator image to 1.30.0
  jaeger-operator/Dockerfile
Labels: size/XS, lgtm

#179 update version to 1.30.0 in makefile
  jaeger-operator/Makefile
Labels: size/XS, lgtm

#175 Clean up CODEOWNERS
  CODEOWNERS
Labels: size/S, lgtm

#176 Remove the `serverless-bench` folder
  CODEOWNERS
  serverless-bench/Dockerfile
  serverless-bench/Makefile
  serverless-bench/README.md
  serverless-bench/locust.py
  serverless-bench/run-benchmarks.sh
Labels: size/M, lgtm

#180 Add grego952 as a documentation CODEOWNER in Third-Party Images
  CODEOWNERS
Labels: documentation, size/XS, lgtm, area/community, area/documentation

#181 Bump CloudSQL image to v1.28.1
  cloudsql-proxy/Dockerfile
Labels: size/XS, lgtm

#182 Bump etcd alpine base to 3.15.0 and OpenSSL to 1.1.1l-r7
  etcd/Dockerfile
Labels: size/XS, lgtm

#184 patch loki output plugin issue in fluent-bit
  fluent-bit/Dockerfile
Labels: size/XS, lgtm

#187 update to grafana 7.5.15
  grafana/Makefile
Labels: size/XS, lgtm

#185 Install OpenSSL dev from edge
  cloudsql-proxy/Dockerfile
  etcd/Dockerfile
Labels: size/XS, lgtm

#186 Update CODEOWNERS (gophers)
  CODEOWNERS
Labels: size/XS, lgtm

#188 Bump gitea dependency
  kaniko-executer/Dockerfile
Labels: size/XS, lgtm, area/security, area/serverless

#190 Bump kiwigrid/k8s-sidecar
  kiwigrid-sidecar/Dockerfile
  kiwigrid-sidecar/Makefile
Labels: size/XS, lgtm

#189 Update stale.yml
  .github/stale.yml
Labels: size/XS, lgtm
