Repository kyma-project/third-party-images, pull requests merged in 2022-07, with the labels that each got.

#239 update to fluent 1.9.5
  fluent-bit/Dockerfile
  fluent-bit/Makefile
  fluent-bit/plugins/out_sequentialhttp/sequentialhttp.c
  fluent-bit/plugins/out_sequentialhttp/sequentialhttp.h
  fluent-bit/plugins/out_sequentialhttp/sequentialhttp_conf.c
  fluent-bit/plugins/out_sequentialhttp/sequentialhttp_conf.h
Labels: size/M, lgtm

#240 Cloudsql Image Update
  cloudsql-proxy/Dockerfile
  cloudsql-proxy/Makefile
Labels: size/M, lgtm

#241 Corrected Incidental Removal of Slash
  cloudsql-proxy/Makefile
Labels: size/XS, lgtm

#242 Corrected Missing Etc
  cloudsql-proxy/Dockerfile
Labels: size/XS, lgtm

#243 Simplified GCE Proxy Image
  cloudsql-proxy/Dockerfile
Labels: size/S, lgtm
