Repository kyma-project/third-party-images, pull requests merged in 2022-08, with the labels that each got.

#248 bump cloudsql-proxy to latest patch version
  cloudsql-proxy/Dockerfile
Labels: size/XS, lgtm

#249 Update Makefile
  cloudsql-proxy/Makefile
Labels: size/XS, lgtm

#251 update of several alpine base images
  grafana/Dockerfile
  kiali/Dockerfile
  kiwigrid-sidecar/Dockerfile
  loki/Dockerfile
  oauth2-proxy/Dockerfile
  prometheus-node-exporter/Dockerfile
Labels: size/S, lgtm

#252 Remove unused minio image
  minio/Dockerfile
  minio/Makefile
  minio/README.md
Labels: size/M, lgtm

#256 Bump kubectl version to 1.23.10 in k8s-tools
  k8s-tools/Dockerfile
Labels: size/XS, lgtm

#257 Update golang version for fluent-bit loki plugin
  fluent-bit/Dockerfile
Labels: size/XS, lgtm

#254 Update images used by docker-registry
  docker-registry/Dockerfile
Labels: size/XS, lgtm

#253 Update images used by kaniko-executor and remove minio
  kaniko-executer/Dockerfile
  kaniko-executer/Makefile
Labels: size/S, lgtm

#250 Update Fluent Bit to 1.9.7
  fluent-bit/Makefile
Labels: size/XS, lgtm
