Repository kyma-project/third-party-images, pull requests merged in 2022-03, with the labels that each got.

#193 Bump cloudsql-gce-proxy ver to 1.29.0
  cloudsql-proxy/Dockerfile
  cloudsql-proxy/Makefile
Labels: size/XS, lgtm

#194 update to fluent-bit 1.8.13
  fluent-bit/Dockerfile
  fluent-bit/Makefile
  loki/Dockerfile
Labels: size/XS, lgtm

#195 update to kiwigrid 1.15.7
  kiwigrid-sidecar/Makefile
Labels: size/XS, lgtm

#197 Update CODEOWNERS
  CODEOWNERS
Labels: size/XS, lgtm

#198 Delete pipelines related with the `minio-mc`
  CODEOWNERS
  minio-mc/Dockerfile
  minio-mc/Makefile
  minio-mc/README.md
Labels: size/S, lgtm, area/serverless

#196 migrate from CODEOWNERS to OWNERS
  .github/ISSUE_TEMPLATE/OWNERS
  .github/OWNERS
  OWNERS
  OWNERS_ALIASES
  cloudsql-proxy/OWNERS
  common/OWNERS
  docker-registry/OWNERS
  etcd/OWNERS
  fluent-bit/OWNERS
  grafana/OWNERS
  jaeger-operator/OWNERS
  k8s-tools/OWNERS
  kaniko-executer/OWNERS
  kiali/OWNERS
  kiwigrid-sidecar/OWNERS
  loki/OWNERS
  minio/OWNERS
  oauth2-proxy/OWNERS
  prometheus-node-exporter/OWNERS
Labels: size/L, lgtm

#199 Bump kubectl in k8s-tools
  k8s-tools/Dockerfile
Labels: size/XS, lgtm

#200 update fluentbit to 1.8.14
  fluent-bit/Dockerfile
  fluent-bit/Makefile
Labels: size/XS, lgtm

#201 update to fluentbit 1.8.15
  fluent-bit/Makefile
Labels: size/XS, lgtm

#202 Upgrade serverless dependencies
  docker-registry/Dockerfile
  kaniko-executer/Makefile
  minio/Dockerfile
Labels: size/XS, lgtm, area/security
