Repository kyma-project/third-party-images, pull requests merged in 2022-04, with the labels that each got.

#203 Remove CODEOWNERS
  .github/stale.yml
  CODEOWNERS
Labels: approved, size/M, lgtm

#205 upgrade base alpine and debian images
  fluent-bit/Dockerfile
  grafana/Dockerfile
  kiali/Dockerfile
  kiwigrid-sidecar/Dockerfile
  kiwigrid-sidecar/Makefile
  loki/Dockerfile
  oauth2-proxy/Dockerfile
  prometheus-node-exporter/Dockerfile
Labels: approved, size/S, lgtm

#206 Upgrade alpine base images for serverless components
  docker-registry/Dockerfile
  kaniko-executer/Dockerfile
  minio/Dockerfile
Labels: size/XS, approved, lgtm

#208 Improve http plugin
  fluent-bit/plugins/out_sequentialhttp/sequentialhttp.c
Labels: approved, size/M, lgtm

#207 Autobump Alpine in k8s-tools image
  .github/dependabot-config.yaml
  .github/dependabot.tmpl
  .github/dependabot.yml
Labels: approved, size/M, lgtm

#211 Cloudsql Image Update
  cloudsql-proxy/Dockerfile
Labels: size/XS, approved, lgtm

#213 Alpine Updates
  cloudsql-proxy/Dockerfile
  etcd/Dockerfile
Labels: size/XS, approved, lgtm

#215 Bump Fluent Bit
  fluent-bit/Dockerfile
  fluent-bit/Makefile
Labels: approved, size/S, lgtm

#216 Set loki plugin go version back to 1.17
  fluent-bit/Dockerfile
Labels: size/XS, approved, lgtm

#217 Bump alpine
  docker-registry/Dockerfile
Labels: size/XS, approved, lgtm

#218 Prepare for Github workflow
  CODEOWNERS
Labels: approved, size/M, lgtm

#219 Bump k8s-tools image
  k8s-tools/Dockerfile
Labels: size/XS, approved, lgtm

#221 Fix documentation CODEOWNERS
  CODEOWNERS
Labels: approved, lgtm

#222 Remove owners files
  .github/ISSUE_TEMPLATE/OWNERS
  .github/OWNERS
  OWNERS
  OWNERS_ALIASES
  cloudsql-proxy/OWNERS
  common/OWNERS
  docker-registry/OWNERS
  etcd/OWNERS
  fluent-bit/OWNERS
  grafana/OWNERS
  jaeger-operator/OWNERS
  k8s-tools/OWNERS
  kaniko-executer/OWNERS
  kiali/OWNERS
  kiwigrid-sidecar/OWNERS
  loki/OWNERS
  minio/OWNERS
  oauth2-proxy/OWNERS
  prometheus-node-exporter/OWNERS
Labels: size/L

#223 update kiali to 1.49
  kiali/Dockerfile
  kiali/Makefile
Labels: size/XS, lgtm
