Repository kyma-project/third-party-images, pull requests merged in 2022-10, with the labels that each got.

#268 Add kube-state-metrics as third party image
  CODEOWNERS
  kube-state-metrics/Dockerfile
  kube-state-metrics/Makefile
  kube-state-metrics/README.md
Labels: size/M, lgtm

#267 Build oauth2 proxy with go ver 1.19
  oauth2-proxy/Dockerfile
Labels: size/S, lgtm

#270 update python version for k8s-sidecar
  kiwigrid-sidecar/Dockerfile
Labels: size/XS, lgtm

#271 updated golang version to 1.19.2 for observability images
  fluent-bit/Dockerfile
  grafana/Dockerfile
  kiali/Dockerfile
  kiwigrid-sidecar/Dockerfile
  kube-state-metrics/Dockerfile
  loki/Dockerfile
  oauth2-proxy/Dockerfile
  prometheus-node-exporter/Dockerfile
Labels: size/M, lgtm

#272 Use golang 1.19.2
  docker-registry/Dockerfile
  kaniko-executer/Dockerfile
Labels: size/S, lgtm

#273 update to oauth2-proxy 7.4.0
  oauth2-proxy/Makefile
Labels: size/XS, lgtm
