Repository kyma-project/third-party-images, pull requests merged in 2022-01, with the labels that each got.

#163 Fetch latest kaniko version
  kaniko-executer/Dockerfile
Labels: size/XS, lgtm

#165 update of base image for several images
  fluent-bit/Dockerfile
  kiwigrid-sidecar/Dockerfile
  kiwigrid-sidecar/Makefile
  loki/Dockerfile
  oauth2-proxy/Dockerfile
Labels: size/S, lgtm

#166 Bump cloudsql-proxy to 1.28.0
  cloudsql-proxy/Dockerfile
  cloudsql-proxy/Makefile
Labels: size/XS, lgtm

#164 Bump golang to golang:1.17.6-alpine3.15
  docker-registry/Dockerfile
  kaniko-executer/Dockerfile
Labels: size/XS, lgtm

#168 update to grafana 7.5.13
  grafana/Makefile
Labels: size/XS, lgtm

#169 Upgrade oauth2 proxy to 7.2.1
  oauth2-proxy/Makefile
  oauth2-proxy/README.md
Labels: size/XS, lgtm

#167 Add serverless-bench image
  CODEOWNERS
  serverless-bench/Dockerfile
  serverless-bench/Makefile
  serverless-bench/README.md
  serverless-bench/locust.py
  serverless-bench/run-benchmarks.sh
Labels: size/M, lgtm

#170 Bump kubectl to 1.21.9 & Alpine to 3.15.0 in k8s-tools
  k8s-tools/Dockerfile
Labels: size/XS, lgtm

#172 Add coreutils to serverless-bench
  serverless-bench/Dockerfile
Labels: size/XS, lgtm

#173 updated codeowners
  CODEOWNERS
Labels: size/S, lgtm

#171 update to fluent-bit 1.8.12
  fluent-bit/Dockerfile
  fluent-bit/Makefile
Labels: size/XS, lgtm
