Repository kyma-project/third-party-images, pull requests merged in 2023-03, with the labels that each got.

#316 Bump kubectl to 1.24.11
  k8s-tools/Dockerfile
Labels: size/XS, lgtm

#317 Update CloudSQL proxy to v1.33.4
  cloudsql-proxy/Dockerfile
  cloudsql-proxy/Makefile
  cloudsql-proxy/envs
Labels: size/XS, lgtm

#318 update of golang, kube-state-metrics, otel-collector
  fluent-bit/envs
  grafana/envs
  kube-state-metrics/envs
  loki/envs
  oauth2-proxy/envs
  otel-collector/envs
Labels: size/S, lgtm

#320 update to fluentbit 2.0.10
  fluent-bit/envs
Labels: size/XS, lgtm, area/telemetry

#319 Update golang builder version to 1.20.2
  docker-registry/Dockerfile
  kaniko-executer/Dockerfile
Labels: size/S, lgtm

#321 add fileexporter and filelogreceiver to otel collector image
  otel-collector/builder-config.yaml
  otel-collector/envs
Labels: size/XS, lgtm

#323 Bump kubectl to 1.25.8
  k8s-tools/Dockerfile
Labels: size/XS, lgtm

#324 Bump Alpine base images to 3.17.3
  kiwigrid-sidecar/envs
  loki/envs
  oauth2-proxy/envs
  prometheus-node-exporter/envs
Labels: size/XS, lgtm
