Repository kyma-project/third-party-images, pull requests merged in 2023-07, with the labels that each got.

#361 Remove Loki
  CODEOWNERS
  loki/Dockerfile
  loki/README.md
  loki/envs
Labels: size/M, lgtm, area/logging, kind/cleanup

#363 Update OpenTelemetry Collector to 0.81.0
  otel-collector/envs
Labels: size/XS, lgtm

#365 Update Fluent Bit to 2.1.7
  fluent-bit/envs
Labels: size/XS, lgtm, area/logging

#364 Bump k8s-sidecar version to 1.24.6
  kiwigrid-sidecar/envs
Labels: size/XS, lgtm

#366 update of golang and alpine for observability components
  alertmanager/envs
  grafana/Dockerfile
  grafana/envs
  kube-state-metrics/envs
  oauth2-proxy/Dockerfile
  oauth2-proxy/envs
  prometheus-node-exporter/envs
Labels: size/S, lgtm
