Repository kyma-project/third-party-images, pull requests merged in 2023-11, with the labels that each got.

#394 feat: Remove cumulativeToDelta
  otel-collector/builder-config.yaml
Labels: size/XS, lgtm

#395 update to otel-collector 0.88.0
  otel-collector/envs
Labels: size/XS, lgtm

#396 add httpcheck receiver to otel-collector bundle
  otel-collector/builder-config.yaml
Labels: size/XS, lgtm

#397 Bump builder images for otter images to
  docker-registry/Dockerfile
  kaniko-executer/Dockerfile
Labels: size/XS, lgtm, area/serverless, kind/cleanup

#398 removal of monitoring components
  CODEOWNERS
  alertmanager/Dockerfile
  alertmanager/README.md
  alertmanager/envs
  grafana/Dockerfile
  grafana/README.md
  grafana/envs
  grafana/go.mod
  grafana/go.sum
  grafana/main.go
  grafana/main_test.go
  kiwigrid-sidecar/Dockerfile
  kiwigrid-sidecar/README.md
  kiwigrid-sidecar/envs
  kube-state-metrics/Dockerfile
  kube-state-metrics/README.md
  kube-state-metrics/envs
  oauth2-proxy/Dockerfile
  oauth2-proxy/README.md
  oauth2-proxy/envs
  prometheus-node-exporter/Dockerfile
  prometheus-node-exporter/README.md
  prometheus-node-exporter/envs
Labels: size/XL, lgtm

#399 Add file storage extension to the OpenTelemetry image
  otel-collector/builder-config.yaml
Labels: size/XS, lgtm, area/logging

#400 update to otel-collector 0.89.0
  otel-collector/envs
Labels: size/XS, lgtm

#401 update to fluentbit 2.2.0
  fluent-bit/envs
Labels: size/XS, lgtm
