Repository kyma-project/third-party-images, pull requests merged in 2023-01, with the labels that each got.

#295 Bump python to latest version
  kiwigrid-sidecar/Dockerfile
  kiwigrid-sidecar/envs
Labels: size/XS, lgtm

#296 Bump curl in k8s-tools image
  k8s-tools/Dockerfile
Labels: size/XS, lgtm

#297 Bump golang runtime to 1.19.4
  loki/Dockerfile
Labels: size/XS, lgtm

#298 Add filterprocessor to OpenTelemtry image
  otel-collector/builder-config.yaml
Labels: size/XS, lgtm

#301 Bump golang alpine image for otters components
  docker-registry/Dockerfile
  kaniko-executer/Dockerfile
  kaniko-executer/Makefile
Labels: size/S, lgtm, area/serverless

#302 Fix kaniko version
  kaniko-executer/envs
Labels: size/XS, lgtm, area/serverless

#303 Remove kaniko makefile
  kaniko-executer/Makefile
Labels: size/S, lgtm, area/serverless

#304 Upgrade Fluent Bit to 2.0
  fluent-bit/Dockerfile
  fluent-bit/Makefile
Labels: size/XS, lgtm

#306 updated alpine, golang and otel-collector version of telemetry/observability images
  fluent-bit/Dockerfile
  fluent-bit/envs
  grafana/Dockerfile
  grafana/envs
  kube-state-metrics/Dockerfile
  kube-state-metrics/envs
  loki/Dockerfile
  loki/envs
  oauth2-proxy/Dockerfile
  oauth2-proxy/envs
  otel-collector/envs
  prometheus-node-exporter/Dockerfile
  prometheus-node-exporter/envs
Labels: size/M, lgtm
