Repository kyma-project/third-party-images, pull requests merged in 2023-05, with the labels that each got.

#334 Make node exporter use latest golang version
  prometheus-node-exporter/Dockerfile
  prometheus-node-exporter/Makefile
  prometheus-node-exporter/envs
Labels: size/M, lgtm

#333 Add alertmanager image
  CODEOWNERS
  alertmanager/Dockerfile
  alertmanager/Makefile
  alertmanager/envs
Labels: size/M, lgtm

#336 Add configmap-reload image
  CODEOWNERS
  configmap-reload/Dockerfile
  configmap-reload/Makefile
  configmap-reload/envs
Labels: size/M, lgtm

#338 Trigger image build
  alertmanager/Dockerfile
  configmap-reload/Dockerfile
Labels: size/XS, lgtm

#339 Bump Golang to 1.20.4 for oauth2-proxy
  oauth2-proxy/envs
Labels: size/XS, lgtm

#340 Bump to golang to latest 1.20.4 to resolve security vulnerabilities
  grafana/envs
Labels: size/XS, lgtm

#342 Bump Golang version for Loki
  loki/envs
Labels: size/XS, lgtm

#341 switch codeowners to teams
  CODEOWNERS
Labels: size/S, lgtm

#343 update otel-collector to 0.77.0 and golang 1.20.4
  otel-collector/envs
Labels: size/XS, lgtm

#346 Bump kubectl in k8s-tools image
  k8s-tools/Dockerfile
Labels: size/XS, lgtm

#347 Change Alertmanager image to Alpine base
  alertmanager/Dockerfile
  alertmanager/Makefile
  alertmanager/envs
Labels: size/S, lgtm
