Repository kyma-project/third-party-images, pull requests merged in 2023-08, with the labels that each got.

#368 remove configmap-reload
  CODEOWNERS
  configmap-reload/Dockerfile
  configmap-reload/README.md
  configmap-reload/envs
Labels: size/M, lgtm

#370 Bump k8s-tools image
  k8s-tools/Dockerfile
Labels: lgtm, area/tools, kind/chore

#378 update monitoring images to alpine 1.18.3 and golang 1.20.7
  alertmanager/envs
  grafana/envs
  kiwigrid-sidecar/envs
  kube-state-metrics/envs
  oauth2-proxy/envs
  prometheus-node-exporter/envs
Labels: size/S, lgtm

#379 update otel-collector 0.83.0 and fluentbit 2.1.8
  fluent-bit/envs
  otel-collector/envs
Labels: size/XS, lgtm
