Repository kyma-project/third-party-images, pull requests merged in 2023-02, with the labels that each got.

#307 switch owners of observability components to github team approach
  CODEOWNERS
Labels: size/S, lgtm

#308 update fluentbit to 2.0.9
  fluent-bit/envs
Labels: lgtm

#310 Bump kubectl to 1.24.10
  k8s-tools/Dockerfile
Labels: size/XS, lgtm

#311 update to alpine 1.17.2
  grafana/Makefile
  kiwigrid-sidecar/Makefile
  loki/Dockerfile
  loki/envs
  oauth2-proxy/envs
  prometheus-node-exporter/envs
Labels: size/S, lgtm

#312 update otel-collector to 0.71.0
  otel-collector/envs
Labels: size/XS, lgtm

#313 update python and alpine version for kiwigrid sidecar
  kiwigrid-sidecar/envs
Labels: size/XS, lgtm

#314 update registry docker image
  docker-registry/Dockerfile
Labels: size/XS, lgtm

#315 update otel-collector version to 0.72.0
  otel-collector/Dockerfile
  otel-collector/builder-config.yaml
  otel-collector/envs
Labels: size/S, lgtm, area/telemetry
