Repository kyma-project/third-party-images, pull requests merged in 2023-10, with the labels that each got.

#387 replaced deprecated loggingexporter with debugexporter
  otel-collector/builder-config.yaml
Labels: size/XS, lgtm

#388 update to otel-collector 0.87.0 and fluentbit 2.1.10
  fluent-bit/envs
  otel-collector/envs
Labels: size/XS, lgtm

#377 reuse compliance
  .reuse/dep5
  LICENSES/Apache-2.0.txt
  README.md
Labels: size/L, lgtm

#392 chore: Remove loki plugin from fluent-bit image
  fluent-bit/Dockerfile
  fluent-bit/README.md
  fluent-bit/envs
  fluent-bit/plugins/out_grafana_loki/buffer.go
  fluent-bit/plugins/out_grafana_loki/client.go
  fluent-bit/plugins/out_grafana_loki/config.go
  fluent-bit/plugins/out_grafana_loki/config_test.go
  fluent-bit/plugins/out_grafana_loki/dque.go
  fluent-bit/plugins/out_grafana_loki/go.mod
  fluent-bit/plugins/out_grafana_loki/go.sum
  fluent-bit/plugins/out_grafana_loki/loki.go
  fluent-bit/plugins/out_grafana_loki/loki_test.go
  fluent-bit/plugins/out_grafana_loki/out_grafana_loki.go
Labels: size/XXL, lgtm, area/telemetry, kind/chore

#393 Bump k8s-tools image
  k8s-tools/Dockerfile
Labels: size/XS, lgtm, area/security, kind/chore
