Repository kyma-project/third-party-images, pull requests merged in 2023-06, with the labels that each got.

#348 updated golang, alpine, otel-collector
  alertmanager/Makefile
  alertmanager/README.md
  alertmanager/envs
  configmap-reload/Makefile
  configmap-reload/README.md
  configmap-reload/envs
  fluent-bit/envs
  grafana/Makefile
  grafana/README.md
  grafana/envs
  kiwigrid-sidecar/Makefile
  kiwigrid-sidecar/README.md
  kiwigrid-sidecar/envs
  kube-state-metrics/Makefile
  kube-state-metrics/README.md
  kube-state-metrics/envs
  loki/Makefile
  loki/README.md
  loki/envs
  oauth2-proxy/Makefile
  oauth2-proxy/README.md
  oauth2-proxy/envs
  otel-collector/Makefile
  otel-collector/README.md
  otel-collector/envs
  prometheus-node-exporter/Dockerfile
  prometheus-node-exporter/Makefile
  prometheus-node-exporter/README.md
  prometheus-node-exporter/envs
Labels: size/L, lgtm

#349 add pprof extension to otel-collector image
  otel-collector/builder-config.yaml
Labels: size/XS, lgtm

#350 update to fluentbit 2.1.4
  fluent-bit/envs
Labels: lgtm, area/logging

#354 Use newest golang
  docker-registry/Dockerfile
  kaniko-executer/Dockerfile
Labels: size/XS, lgtm

#355 Use Golang version 1.20.4 for fluent-bit
  fluent-bit/envs
Labels: size/XS, lgtm, area/telemetry

#357 Use newest alpine
  docker-registry/Dockerfile
Labels: size/XS, lgtm

#358 Bump gce-proxy to 1.33.8
  cloudsql-proxy/Dockerfile
  cloudsql-proxy/Makefile
  cloudsql-proxy/envs
Labels: size/XS, lgtm

#359 Bump k8s-tools image
  k8s-tools/Dockerfile
Labels: size/XS, lgtm

#356 Added cumulativetodelta processor into otel distro
  otel-collector/builder-config.yaml
  otel-collector/envs
Labels: size/XS, lgtm

#351 update to node-exporter 1.6.0
  prometheus-node-exporter/envs
Labels: size/XS, lgtm, area/monitoring

#362 Update Python to 3.11.4 for k8s-sidecar
  kiwigrid-sidecar/envs
Labels: size/XS, lgtm

#352 update kube-state-metrics to 2.9.2
  kube-state-metrics/envs
Labels: size/XS, lgtm, area/monitoring
