Repository kyma-project/third-party-images, pull requests merged in 2023-04, with the labels that each got.

#325 Build Grafana with new Alpine base image
  grafana/Makefile
Labels: size/XS, lgtm

#326 update to fluentbit 2.0.11
  fluent-bit/envs
Labels: size/XS, lgtm

#327 Update Golang Builder Version to 1.20.3
  docker-registry/Dockerfile
  kaniko-executer/Dockerfile
Labels: size/XS, lgtm

#328 update to golang 1.20.3 for observability images, update to otel-collector 0.75.0
  fluent-bit/envs
  grafana/envs
  kube-state-metrics/envs
  loki/envs
  oauth2-proxy/envs
  otel-collector/envs
  prometheus-node-exporter/envs
Labels: size/S, lgtm

#330 Bump kubectl in k8s-tools
  k8s-tools/Dockerfile
Labels: size/XS, lgtm

#329 Remove Jaeger docker image
  CODEOWNERS
  jaeger-operator/Dockerfile
  jaeger-operator/Makefile
  jaeger-operator/README.md
  jaeger-operator/envs
Labels: size/M, lgtm

#332 Bump gce-proxy to 1.33.6
  cloudsql-proxy/Dockerfile
  cloudsql-proxy/Makefile
  cloudsql-proxy/envs
Labels: size/XS, lgtm
