Repository kyma-project/third-party-images, pull requests merged in 2024-07, with the labels that each got.

#440 chore: Migrate third party images for fluent-bit and telemetry-self-monitor to Github Actions
  .github/workflows/build-fluentbit-image.yml
  .github/workflows/build-telemetry-self-monitor-image.yml
Labels: size/L, lgtm, cla: yes

#442 chore: Fix builder tag typo, add more PR condition types
  .github/workflows/build-fluentbit-image.yml
  .github/workflows/build-telemetry-self-monitor-image.yml
Labels: kind/bug, size/S, lgtm, cla: yes

#443 chore: Switched steps order to run fetch env file before build args to fix pr workflow
  .github/workflows/build-fluentbit-image.yml
  .github/workflows/build-telemetry-self-monitor-image.yml
Labels: size/S, lgtm, cla: yes

#441 bump fluent bit to 3.1.1
  fluent-bit/envs
Labels: size/XS, lgtm, cla: yes

#446 Remove otters components
  docker-registry/Dockerfile
  docker-registry/README.md
  docker-registry/envs
  kaniko-executer/Dockerfile
  kaniko-executer/README.md
  kaniko-executer/envs
Labels: size/L, lgtm, area/serverless, kind/chore, cla: yes

#445 bump fluent bit to 3.1.3
  fluent-bit/Dockerfile
  fluent-bit/envs
Labels: size/XS, lgtm, cla: yes

#448 fix self-monitor workflow
  .github/workflows/build-telemetry-self-monitor-image.yml
Labels: size/XS, lgtm, cla: yes

#449 fix self-monitor workflow
  .github/workflows/build-fluentbit-image.yml
  .github/workflows/build-telemetry-self-monitor-image.yml
Labels: size/XS, lgtm, cla: yes

#447 update self-monitor to prometheus 2.53.1
  telemetry-self-monitor/envs
Labels: size/XS, lgtm, cla: yes
