Repository kyma-project/third-party-images, pull requests merged in 2024-04, with the labels that each got.

#426 re-introduce envs files
  cloudsql-proxy/Dockerfile
  cloudsql-proxy/envs
  docker-registry/Dockerfile
  docker-registry/envs
  fluent-bit/Dockerfile
  fluent-bit/envs
  kaniko-executer/Dockerfile
  kaniko-executer/envs
  otel-collector/Dockerfile
  telemetry-self-monitor/Dockerfile
  telemetry-self-monitor/envs
Labels: size/S, lgtm, cla: yes

#427 Update OTEL image version to 0.99.0
  otel-collector/envs
Labels: size/XS, lgtm, area/telemetry, kind/chore, cla: yes

#428 Update fluent-bit image version to 3.0.3
  fluent-bit/envs
Labels: size/XS, lgtm, area/logging, area/telemetry, kind/chore, cla: yes
