Repository kyma-project/third-party-images, pull requests merged in 2024-03, with the labels that each got.

#420 chore: Bump otel collector version to 0.96
  otel-collector/envs
Labels: size/XS, lgtm, area/telemetry, kind/chore, cla: yes

#422 add feature gate to otel-collector to use LocalHost As Default Host
  otel-collector/Dockerfile
Labels: size/XS, lgtm, cla: yes

#421 Introduce self-monitor dockerfile
  CODEOWNERS
  telemetry-self-monitor/Dockerfile
  telemetry-self-monitor/README.md
  telemetry-self-monitor/envs
  telemetry-self-monitor/plugins.yml
Labels: size/M, lgtm, area/telemetry, cla: yes

#423 update resty version in otel-collector
  otel-collector/builder-config.yaml
Labels: size/XS, lgtm, cla: yes

#424 update to otel-collector 0.97.0
  otel-collector/envs
Labels: size/XS, lgtm, cla: yes
