Repository kyma-project/third-party-images, pull requests merged in 2024-09, with the labels that each got.

#453 docs: Add mandatory sections to README.md
  README.md
Labels: size/S, lgtm, cla: yes

#454 Delete cloudsql-proxy directory
  cloudsql-proxy/Dockerfile
  cloudsql-proxy/Makefile
  cloudsql-proxy/README.md
  cloudsql-proxy/envs
Labels: size/S, lgtm, cla: yes

#455 Delete k8s-tools directory
  k8s-tools/Dockerfile
  k8s-tools/Makefile
  k8s-tools/README.md
Labels: size/M, lgtm, cla: yes

#456 cleanup self-monitor
  .github/workflows/build-telemetry-self-monitor-image.yml
  CODEOWNERS
  telemetry-self-monitor/Dockerfile
  telemetry-self-monitor/README.md
  telemetry-self-monitor/envs
  telemetry-self-monitor/plugins.yml
Labels: size/L, lgtm, cla: yes
